# Generated by Django 5.0.7 on 2024-08-01 19:30

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Grid01dd",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("xcol", models.BigIntegerField(null=True)),
                ("yrow", models.BigIntegerField(null=True)),
                ("csq", models.CharField(max_length=255, null=True)),
                ("cell", models.CharField(max_length=255, null=True)),
                (
                    "corr_cell",
                    django.contrib.gis.db.models.fields.GeometryField(
                        null=True, srid=4326
                    ),
                ),
                ("geom_rel", models.CharField(max_length=255, null=True)),
                ("g1d_id", models.BigIntegerField(null=True)),
                ("drained_m2", models.BigIntegerField(null=True)),
                ("cent_x_geo", models.FloatField(null=True)),
                ("cent_y_geo", models.FloatField(null=True)),
                ("id_netcdf", models.BigIntegerField(null=True)),
                ("cty_id", models.CharField(max_length=255, null=True)),
                ("within_igad", models.BooleanField(null=True)),
                ("admin1_f_id", models.BigIntegerField(null=True)),
                ("populations_2020", models.FloatField(null=True)),
                ("g005d_id", models.BigIntegerField(null=True)),
                ("population_2020", models.FloatField(null=True)),
                ("country_iso", models.CharField(max_length=3, null=True)),
                ("level1_id", models.BigIntegerField(null=True)),
                ("g083d_id", models.BigIntegerField(null=True)),
                ("gadm3_id", models.BigIntegerField(null=True)),
                ("area_km2", models.FloatField(null=True)),
                ("size_km", models.FloatField(null=True)),
                ("in_lake", models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Soil",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("year", models.BigIntegerField(null=True)),
                ("anomaly_jan", models.FloatField(null=True)),
                ("anomaly_feb", models.FloatField(null=True)),
                ("anomaly_mar", models.FloatField(null=True)),
                ("anomaly_apr", models.FloatField(null=True)),
                ("anomaly_may", models.FloatField(null=True)),
                ("anomaly_jun", models.FloatField(null=True)),
                ("anomaly_jul", models.FloatField(null=True)),
                ("anomaly_aug", models.FloatField(null=True)),
                ("anomaly_sep", models.FloatField(null=True)),
                ("anomaly_oct", models.FloatField(null=True)),
                ("anomaly_nov", models.FloatField(null=True)),
                ("anomaly_dec", models.FloatField(null=True)),
                ("updated_when", models.DateTimeField(null=True)),
                (
                    "g0d_id",
                    models.ForeignKey(
                        db_column="g0d_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soils",
                        to="igad_kenya.grid01dd",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SPI",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("init_month", models.CharField(max_length=255, null=True)),
                ("init_year", models.BigIntegerField(null=True)),
                ("lead_time", models.IntegerField(null=True)),
                ("prec", models.FloatField(null=True)),
                ("spi_01", models.FloatField(null=True)),
                ("spi_03", models.FloatField(null=True)),
                ("spi_06", models.FloatField(null=True)),
                ("spi_09", models.FloatField(null=True)),
                ("spi_12", models.FloatField(null=True)),
                ("spi_15", models.FloatField(null=True)),
                ("spi_24", models.FloatField(null=True)),
                ("spi_30", models.FloatField(null=True)),
                ("updated_when", models.DateTimeField(null=True)),
                (
                    "g0d_id",
                    models.ForeignKey(
                        db_column="g0d_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spis",
                        to="igad_kenya.grid01dd",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Temperature",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("init_month", models.CharField(max_length=255, null=True)),
                ("init_year", models.BigIntegerField(null=True)),
                ("pred_month", models.CharField(max_length=255, null=True)),
                ("prob_below", models.FloatField(null=True)),
                ("prob_above", models.CharField(max_length=255, null=True)),
                ("prob_normal", models.FloatField(null=True)),
                ("updated_when", models.DateTimeField(null=True)),
                (
                    "g0d_id",
                    models.ForeignKey(
                        db_column="g0d_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temperatures",
                        to="igad_kenya.grid01dd",
                    ),
                ),
            ],
        ),
    ]
